### PR TITLE
Users/jacdavis

### PR DESCRIPTION
**Pull request by jacdavis**
Fix working directory for lldb launch.

    Normally, we set the working dir using the -environment-cd
    mi command. lldb does support this command, but sadly, it doesn't
    work, at least on mac. Instead, I'm setting the working dir
    of lldb at launch which will carry over to the debuggee.

### CODE REVIEW

**Comment by jacdavis** [comment]
@gregg-miskelly @pieandcakes @edumunoz

**Comment by pieandcakes** [comment]
:shipit:

**Comment by edumunoz** [comment]
Does this affect the ability of `lldb-mi` to find other binaries in its current directory (e.g., `debugserver`)?

**Comment by jacdavis** [comment]
Doesn’t seem to. Testing isn’t finding any issue with that.

**Comment by edumunoz** [comment]
`lldb-mi` will use the system provided `debugserver` if it can't find the one beside it.
I would double check it's not using that one.

**Pull request merged**
