### PR TITLE
remove legacy methods required by Kofe

### PR DESCRIPTION
**Pull request by faxue-msft**
I'll update the Kofe side accordingly. We need to re-ship Kofe binary for dev15 to fix the binary version.

### CODE REVIEW

**Comment by faxue-msft** [comment]
@gregg-miskelly

**Comment by gregg-miskelly** [comment]
LGTM

**Comment by chuckries** [comment]
@dotnet-bot build this please

**Comment by chuckries** [comment]
@dotnet-bot build please

**Comment by chuckries** [comment]
@dotnet-bot test this please

**Comment by chuckries** [comment]
:+1:

**Pull request merged**
