### PR TITLE
Function breakpoints

### PR DESCRIPTION
**Pull request by olizit**
Add function breakpoints feature

### CODE REVIEW

**Comment by chuckries** [comment]
@olizit Thanks for this contribution! We are locking down MIEngine to prep for release. If you would like this change to be in the release, please respond to this feedback and have it merged by 3 P. M. PST tomorrow (Wednesday, February 10th). At that time we will be merging the current master branch into the release branch. If you can't get to it, this change won't be included into MIEngine until it's next release. Thanks again!

**Comment by olizit** [comment]
I've commited this : https://github.com/olizit/MIEngine/commit/64e1f2113f60efecfca4bb3368767c8f7a45048d

**Comment by chuckries** [comment]
@wiktork can you sign off on this?

**Comment by gregg-miskelly** [comment]
:+1:

**Pull request merged**
