### PR TITLE
Fix for LLDB to allow exe arguments on launch

### PR DESCRIPTION
**Pull request by pieandcakes**
Reorder launch parameters to run -exec-arguments after
-file-exec-and-symbols

### CODE REVIEW

**Comment by pieandcakes** [comment]
@richardstanton @gregg-miskelly @chuckries

**Comment by pieandcakes** [comment]
Verified this did not break the gdb case on Ubuntu

**Comment by richardstanton** [comment]
# 👍

**Comment by gregg-miskelly** [comment]
:shipit:

**Comment by chuckries** [comment]
seems like this would be worth fixing in lldb-mi as well, but whatever.

**Pull request merged**
