### PR TITLE
Make the MIEngine project buildable in Dev15

### PR DESCRIPTION
**Pull request by gregg-miskelly**
This checkin makes the changes to the MIEngine projects so that they are buildable/launchable in Dev15.

Testing:
- Verified that the project can be built from the IDE and from build.cmd in both Dev14 and Dev15
- Verified that, when building in Dev14, we get exactly the same IL as before
- Verified that we can launch the project in Dev15

### CODE REVIEW

**Comment by faxue-msft** [comment]
Build.cmd still depends on VS140COMNTOOLS to work properly, how will it work when Dev15 is installed?

**Comment by faxue-msft** [comment]
otherwise LGTM

**Comment by gregg-miskelly** [comment]
Build.cmd will work now as long as it is run from a Dev command prompt.

Dev15 doesn't add any global environment variables, so I can't make the equivalent code work unless I sniff the Dev15 install directory. I am tempted to think we should just run it from a dev command prompt unless that is hard to do.

**Comment by gregg-miskelly** [comment]
I will update the error message though.

**Pull request merged**
