### PR TITLE
Don't hardcode path to kill in UnixUtilities

### PR DESCRIPTION
**Pull request by expipiplus1**
Fixes https://github.com/microsoft/vscode-cpptools/issues/10124#issuecomment-1307655686

### CODE REVIEW

**Review by WardenGnaw — APPROVED** [review]

**Review by gregg-miskelly — APPROVED** [review]

**Comment by expipiplus1** [comment]
Thanks :)

**Comment by gregg-miskelly** [comment]
@WardenGnaw are the Linux failures just known flakeyness?

**Comment by WardenGnaw** [comment]
> @WardenGnaw are the Linux failures just known flakeyness?

Re-running to double check. I don't recall seeing these failures before.

**Comment by WardenGnaw** [comment]
Different test failed this time. Linux tests are flaky.

**Comment by WardenGnaw** [comment]
Thank you for your contribution @expipiplus1

**Comment by expipiplus1** [comment]
Thank you for the quick turnaround on this!

**Pull request merged**
