### PR TITLE
Use SIGTRAP to interrupt a process instead of SIGINT

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
Because of https://bugzilla.kernel.org/show_bug.cgi?id=9039, when
a program blocks a signal because it uses sigwait() or signalfd(),
GDB isn't notified of the signal via ptrace and cannot intercept it.

For MIEngine, this means that whenever MIEngine attaches to a process
using signalfd() or sigwait() to process SIGINT, any SIGINT signal
sent by MIEngine to interrupt gdb is delivered to the process instead
which usually handles the signal by exiting.

As a workaround, let's use SIGTRAP instead. SIGTRAP is explicitly
defined as a signal to inform the debugger that some condition has
occurred that it has requested to be informed of. As such, it is a
lot less likely to be blocked by programs compared to SIGINT. Because
it isn't blocked most of the time, gdb will be able to intercept it
and it won't be delivered to the program.

```
SIGTRAP
   ; The SIGTRAP signal is sent to a process when an exception (or trap) occurs: a condition that a debugger has requested to be informed of — for example, when a particular function is executed, or when a particular variable changes value.
```

Fixes https://github.com/microsoft/vscode-cpptools/issues/6704.

### CODE REVIEW

**Comment by DaanDeMeyer** [comment]
Not tested as I don't have access to a Windows installation.

I did test the logic manually by attaching gdb to a process using signalfd() and running continue. Sending SIGINT to that same process caused the process to exit. Sending SIGTRAP instead caused gdb to interrupt as expected.

**Comment by DaanDeMeyer** [comment]
@WardenGnaw Anything I can do to speed this along? I'd love to test this on Windows but I only have a Linux system at hand unfortunately.

**Comment by WardenGnaw** [comment]
@DaanDeMeyer Sorry for the delay, theres a couple of things in the backlog to catch up over the holidays.

I'll see if I can spin up a build and test this soon.  

I can also drop a C++ Extension vsix with the updated binaries.

**Comment by DaanDeMeyer** [comment]
A vsix would be great! I can post my own test results back here then.

**Comment by WardenGnaw** [comment]
Here is the linux-x64 vsix. 
[cpptools-linux.zip](https://github.com/microsoft/MIEngine/files/5805658/cpptools-linux.zip)

I am noticing an error when disconnecting an attach and reattaching to the process.

**Comment by DaanDeMeyer** [comment]
For me, when using the provided vsix, the debug session shuts down after I select a remote process from the picker without outputting any logging info. When using the official release, the extension attaches to the process as expected and produces logging output (but crashes the debuggee process whenever setting a breakpoint).

I assume this is due to a bug introduced by these changes (although it could also be due to another change introduced since the latest cpptools release). Since I don't have an easy way of building the extension, I'll hope that you find some time to look at this sometime to see if we can't make this work somehow.

Somewhat related, it'd be cool if one of the Azure pipelines builds could produce a vsix as output. That way, even users without Windows could do some small development by downloading the vsix file produced by MIEngine's CI which they could install and do testing with.

**Comment by DaanDeMeyer** [comment]
@WardenGnaw Could you test or upload a vsix one more time? I had another look and found out I forgot to update the code that checks if a received signal is an async break signal.

**Comment by WardenGnaw** [comment]
Here is the linux vsix built off of https://github.com/microsoft/MIEngine/commit/d24439cc2659c7bc48bab47e841c8f7ad6fc3341: 
[cpptools-linux.zip](https://github.com/microsoft/MIEngine/files/5857937/cpptools-linux.zip)

**Comment by DaanDeMeyer** [comment]
Can I bother you once more to build a vsix of the master branch as well so I can verify that the master branch works correctly? I'm running into an issue where the debugger exits and I get no logging output at all so I want to make sure that I'm not running into another issue not caused by my changes.

**Comment by DaanDeMeyer** [comment]
I found a stacktrace in the extension host logs:

```
[2021-01-22 20:59:37.563] [exthost] [error] SyntaxError: Unexpected token f
	at unexpected (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25228:17)
	at expect (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25273:5)
	at parse_object (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25389:7)
	at walk (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25496:12)
	at parse_array (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25471:29)
	at walk (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25501:12)
	at parse_object (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25421:33)
	at walk (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25496:12)
	at Object.parse (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:25548:16)
	at ConfigurationSnippetProvider.provideCompletionItems (/home/daan/.vscode/extensions/ms-vscode.cpptools-1.2.0-sigtrap2/dist/main.js:50159:39)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:764:65
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:1010
	at new Promise (<anonymous>)
	at Object.t.asPromise (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:982)
	at H.provideCompletionItems (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:764:36)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:781:242
	at q._withAdapter (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:772:10)
	at q.$provideCompletionItems (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:781:220)
	at m._doInvokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:926)
	at m._invokeHandler (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:892:618)
	at m._receiveRequest (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:891:201)
	at m._receiveOneMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:890:6)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:888:136
	at l.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1094:104
	at l.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at v.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:238:1004)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:235:927
	at l.fire (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:801)
	at p.acceptChunk (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:231:195)
	at /opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:230:547
	at Socket.t (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

It seems this is unrelated to MIEngine or my changes.

**Comment by WardenGnaw** [comment]
Shoot, this might be due to the VS Code extension dependencies. 

You can use the latest working extension code, so we can ignore any dependencies there and rename vsix as .zip, and then you can copy the debugAdapter folder from the zip into your ~/.vscode/extensions/<cpptools>/.

This should work around the js dependencies that are irrelevant.

**Comment by DaanDeMeyer** [comment]
That removes the stacktrace but it seems the debugger still won't start for some reason. If I start debugging in a container, I can select the remote process using the remote process picker, then the debug UI appears for a few seconds and then the debug UI disappears.

This is the only output from the C/C++ extension window:

```
Launch configuration:
{
  "type": "cppdbg",
  "program": "/usr/lib/systemd/systemd-resolved",
  "processId": "351",
  "request": "attach",
  "name": "Attach",
  "pipeTransport": {
    "pipeProgram": "mkosi",
    "pipeArgs": [
      "-C",
      "/home/daan/projects/systemd",
      "ssh"
    ],
    "debuggerPath": "/usr/bin/gdb"
  },
  "MIMode": "gdb",
  "logging": {
    "trace": true,
    "traceResponse": true,
    "engineLogging": true
  },
  "__configurationTarget": 5
}
```

launch.json:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cppdbg",
            "program": "/usr/lib/systemd/systemd-resolved",
            "processId": "${command:pickRemoteProcess}",
            "request": "attach",
            "name": "Attach",
            "pipeTransport": {
                "pipeProgram": "mkosi",
                "pipeArgs": [
                    "-C", "${workspaceFolder}",
                    "ssh"
                ],
                "debuggerPath": "/usr/bin/gdb",
            },
            "MIMode": "gdb",
            "logging": {
                "trace": true,
                "traceResponse": true,
                "engineLogging": true
            },
        }
    ]
}

```

Using the official release of the C/C++ extension, the debugger starts and attaches to the remote process as expected. I also turned on the language server debugging (even though I have it disabled) but that didn't give me any extra logs either.

**Comment by DaanDeMeyer** [comment]
Still nothing after using the exact same permissions from the official release files for the dev build files.

**Comment by DaanDeMeyer** [comment]
Hacked some stuff in the debugger shell script to redirect stderr to a file and got the following stacktrace out of it:

```
+++ dirname /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/OpenDebugAD7
++ cd /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters
++ pwd -P
+ BIN_DIR=/home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters
+ PLATFORM_SUFFIX=
+ ARCH_SUFFIX=
+ case `uname` in
++ uname
+ PLATFORM_SUFFIX=.linux
+ case `uname -m` in
++ uname -m
+ ARCH_SUFFIX=-x86_64
+ MONO_CMD=/home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/mono.linux-x86_64
+ '[' '!' -e /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/mono.linux-x86_64 ']'
+ export MONO_PATH=/home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/framework
+ MONO_PATH=/home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/framework
+ MONO_ARGS=("--config" "${BIN_DIR}/framework/config${PLATFORM_SUFFIX}")
+ /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/mono.linux-x86_64 --config /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/framework/config.linux /home/daan/.vscode/extensions/ms-vscode.cpptools-1.1.3/debugAdapters/bin/OpenDebugAD7.exe
waiting for v8 protocol on stdin/stdout

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Utilities.ConvertUtils' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
   --- End of inner exception stack trace ---
  at Newtonsoft.Json.Serialization.DefaultContractResolver.IsJsonPrimitiveType (System.Type t) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x0003e] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00016] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00028] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.TraceMessage (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.ProtocolMessage message, System.String rawText, System.Boolean isSend, System.Boolean isCancelled, System.Nullable`1[T] duration) [0x0008c] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.SendMessageCore (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.ProtocolMessage message) [0x00014] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.SendEventCore (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.DebugEvent evt) [0x00052] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugProtocolClient.SendEvent (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.DebugEvent evt) [0x00000] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at OpenDebugAD7.DebugEventLogger.WriteTrace (OpenDebugAD7.LoggingCategory category, System.String message) [0x0002c] in <92febf837f5e4a68a88d545070439c29>:0 
  at OpenDebugAD7.DebugEventLogger.TraceLogger_EventHandler (System.Object sender, Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.LogEventArgs args) [0x0003f] in <92febf837f5e4a68a88d545070439c29>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.Log (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.LogCategory category, System.String message) [0x0003f] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleFatalError (System.Exception ex) [0x00059] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc () [0x000a8] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <2943701620b54f86b436d3ffad010412>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.Utilities.ConvertUtils' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
   --- End of inner exception stack trace ---
  at Newtonsoft.Json.Serialization.DefaultContractResolver.IsJsonPrimitiveType (System.Type t) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract (System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract (System.Type type) [0x0003e] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe (System.Object value) [0x00016] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00028] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonSerializer.SerializeInternal (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00253] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonSerializer.Serialize (Newtonsoft.Json.JsonWriter jsonWriter, System.Object value, System.Type objectType) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObjectInternal (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializer jsonSerializer) [0x00028] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x00007] in <607e95f78559498690f968784b884761>:0 
  at Newtonsoft.Json.JsonConvert.SerializeObject (System.Object value, Newtonsoft.Json.JsonSerializerSettings settings) [0x00000] in <607e95f78559498690f968784b884761>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.TraceMessage (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.ProtocolMessage message, System.String rawText, System.Boolean isSend, System.Boolean isCancelled, System.Nullable`1[T] duration) [0x0008c] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.SendMessageCore (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.ProtocolMessage message) [0x00014] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.SendEventCore (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.DebugEvent evt) [0x00052] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugProtocolClient.SendEvent (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Messages.DebugEvent evt) [0x00000] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at OpenDebugAD7.DebugEventLogger.WriteTrace (OpenDebugAD7.LoggingCategory category, System.String message) [0x0002c] in <92febf837f5e4a68a88d545070439c29>:0 
  at OpenDebugAD7.DebugEventLogger.TraceLogger_EventHandler (System.Object sender, Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.LogEventArgs args) [0x0003f] in <92febf837f5e4a68a88d545070439c29>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.Log (Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.LogCategory category, System.String message) [0x0003f] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleFatalError (System.Exception ex) [0x00059] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc () [0x000a8] in <e1fd70d6c9c9452f972cbd12376bac46>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <2943701620b54f86b436d3ffad010412>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <2943701620b54f86b436d3ffad010412>:0 
```

**Comment by DaanDeMeyer** [comment]
Fixed the issue by installing mono so System.Numerics could be found.

Debugger doesn't crash the application anymore when debugging. Will do a more thorough test tomorrow.

**Comment by DaanDeMeyer** [comment]
@WardenGnaw I did a more thorough test and this works as I expected. Setting and removing breakpoints after attaching to the remote process works and doesn't crash the process anymore as was the case with SIGINT.

I did find another issue with sourceFileMap but I will make a different issue for that.

**Comment by WardenGnaw** [comment]
I'll do some validation and then complete if its good. 

Sorry for the delay, we are in the middle of getting for another release but I hope to get this in the next VS Code insiders.

**Comment by DaanDeMeyer** [comment]
@WardenGnaw Any update on the status of merging this?

**Comment by DaanDeMeyer** [comment]
@WardenGnaw Any update on this?

**Comment by WardenGnaw** [comment]
I have not had the time to validate yet, but it is on my list for next week. I will handle merge conflicts and completing the PR

**Review by WardenGnaw — APPROVED** [review]

**Comment by WardenGnaw** [comment]
Tested:
| Scenario  | Platform     | Status     |
| :------------- | :----------: | -----------: |
|  Launch | Windows (MinGW)  | ✅    |
|  Launch | Windows (MinGW)  | ✅    |

**Comment by WardenGnaw** [comment]
@DaanDeMeyer Thank you for your contirubtion to MIEngine!

We will target this for the next VSCode C++ Extension's insiders release.

It will appear in the CHANGELOG when it is available to use in the extension.

**Pull request merged**
