### PR TITLE
Turn on conditinal breakpoints for clrdbg

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@gregg-miskelly @caslan

**Comment by gregg-miskelly** [comment]
:shipit:

**Comment by wesrupert** [comment]
:+1:

**Comment by chuckries** [comment]
@gregg-miskelly I will wait to merge this until the referenced clrdbg package actually supports conditional bp's.

**Comment by chuckries** [comment]
I am merging this so I can produce a new package to reference from the C# extension. The current version of clrdbg that is referenced by the extension supports conditional BP's now.

**Pull request merged**
