### PR TITLE
Support of BlackBerry devices

### PR DESCRIPTION
**Pull request by phofman**
Hi,

I finally managed to finalize the integration of BlackBerry-specific GDB.
The discussion about it was initially started in [issue #44](/Microsoft/MIEngine/issues/44), but I went a little bit further with my implementation. You need to have installed [BlackBerry plugin v3.7.0 for Visual Studio 2015](https://visualstudiogallery.msdn.microsoft.com/2b21e9d1-a54b-4d58-878f-2d53604e85b1) to see it running. All previous versions won't let run (and serialize options for) MIEngine at all.

Big picture:
 * I created dedicated launch options and launcher not to mess to much with existing _generic_ implementations

* BB GDB has a dedicated set of startup commands

 * GDB used by BlackBerry comes from QNX environment and even if docs say differently, the reality is it **doesn't support** async MI execution; to overcome this situation I use a dedicated 'host' application that generates CTRL+C signal to stop running GDB and start accepting MI commands; in code it's accessible through IBreakHandler interface

 * I added some very basic tests

 * this GDB doesn't implement `-exec-abort` command, I use `kill` instead

 * I changed the way `UseUnixSymbolPaths` was evaluated

Let me know, what do you think about it.
Thanks!

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
Hey Paweł, 

First off, it is very cool that you got this to work and we are really happy that you are making Visual Studio better by adding Blackberry support. However we want to make sure the official MIEngine repo contains only code that Visual Studio can commit to being the long term owner of.  While there are parts of these changes that we would be happy to accept, there are also a lot of Blackberry-specific code in this PR that we cannot commit to own.

So that leaves us with two options, and we will leave it up to you which one you go with –
#1 – You could refactor your code to have the blackberry launcher + blackberry launch options XSD in its own repo, and you could submit a PR for adding the hooks you need to MICore. I think that would mean the changes to support IBreakHandler, support for UseUnixSymbolPaths, and the ‘BlackBerryLaunchOptions’->CLSID mapping.
#2 – You could maintain your own fork of the MIEngine so that you can continue to ship with your own ship schedule. See https://github.com/Microsoft/MIEngine/wiki/Redistribution for more information if you go down this route.

Thanks,
Gregg

**Comment by phofman** [comment]
Hi Gregg,

Thanks and sorry for the delayed response.
All true, I understand your point of view about rejection and respect it. Especially I don't want to ask you to support BlackBerry-specific, 5-years old, non-asynchronous GDB (nor buy their devices etc.), if this doesn't match your project's assumptions. I would offer my help on that front, but that just adds another layer of potential complications to the way your project is driven.

Anyway... I don't want to release MIEngine on my own. That's why I would vote for option #1. It also matches the approach I took about dedicated port-supplier. It could stay inside the [BlackBerry plugin](/phofman/vs-plugin) repo directly, as this plugin must be installed to make the whole stack to work.

I can handle the refactoring. Feel free to reject current pull-request. I will start another branch, at the moment I started the implementation and patch MIEngine without any BlackBerry-specific code. Your history will stay clean that way. Although few thing just keep bothering me, if I move the code to my repo. Maybe you have some thoughts about it. They are:
 - I would need to create an interface for a service to parse the *LaunchOptions* content and produce the instance; simple mapping LaunchOptions <-> CLSID is not enough; interface for that service would need to be defined in MIEngine Core, while implementation would stay next to the BB-LaunchOptions; there must be a way to pass me the XML (content or reader) for processing
 - MIEngine should of course handle situation, when this launcher-args-parser (no matter, how named) is not registered in VS2015-hive registry node
 - how could I reference the MIEngine library? my whole project would depend on it as source of all the required interfaces? it's not installed in GAC, rather somewhere inside VS folder; not mentioning it should be possible to correctly start my BB-plugin even, if MIEngine is not installed, as this is possible combination; how should I handle it in my dev-environment, where I could introduce changes on both fronts (BB-plugin and MIEngine) and ci-environment, to just produce "official releases"
 - what about the GDB termination? BB-GDB uses totally different command, will you merge it into master repo or I need to come up with a different way of invoking it?

Cheers,
 Paweł

**Comment by gregg-miskelly** [comment]
Thanks Paweł,
RE: there must be a way to pass me the XML (content or reader) for processing -
I would recommend in LaunchOptions.cs doing something like this:

    case "BlackBerryLaunchOptions":  
    {  
        // NOTE: external customer launchers implement their own XML deserialization
        launcherXmlOptions = options;
        clsidLauncher = new Guid("43BC8C7F-5184-4FE8-9ECF-F33A498375EE");  
    }  
    break;

This should allow the launch options to be passed to your launcher as a string, and you can deserialize them yourself. This is actually how we used to implement the Android and iOS launchers as well.

RE: MIEngine should of course handle situation, when this launcher-args-parser (no matter, how named) is not registered in VS2015-hive registry node
Agreed. You should be able to throw an exception in this case.

RE: how could I reference the MIEngine library?
You could either -
1. Publish a Microsoft.MICore.dll binary that you can build against - checkin and/or fetch from someplace else (ex: OneDrive/DropBox share, or some HTTP endpoint that you have access to), Microsoft.MICore.dll.
-or-
2. You could build a 'contract' version of Microsoft.MICore.dll - this doesn't work quite yet, but pretty soon we expect to have the Microsoft.MICore build produce a 'contract' C# file, which is a C# file that has the same shape as the real thing, but all the methods just throw NotImplementedException. You can then checkin+build this file in another repo, such as yours, in some sort of 'prebuild' step.
-or-
3. You could have some sort of 'prebuild' project which kicks off a build of the MIEngine. In the VSCodeRefactor branch we have added a ['prebuild' project](https://github.com/Microsoft/MIEngine/blob/VSCodeRefactor/src/prebuild/prebuild.csproj) to do some steps, and you could do something similar - in your case, building the MIEngine sln.

**Comment by gregg-miskelly** [comment]
<Sorry, GitHub stopped letting me edit the above comment. Continuing...>

RE: what about the GDB termination?
We actually have an (issue)[https://github.com/Microsoft/MIEngine/issues/19] about this on other platforms too. I _think_ you could safely change the MICommand for GDB to always use 'kill'.

**Comment by phofman** [comment]
Thanks a lot Gregg! I will follow your instructions.

**Pull request closed without merging**
