### PR TITLE
Updating version of clrdbg to get fixes.

### PR DESCRIPTION
**Pull request by rajkumar42**

### CODE REVIEW

**Comment by rajkumar42** [comment]
@gregg-miskelly @chuckries @wesrupert

**Comment by chuckries** [comment]
👍 Do we have any plans to add a new moniker at some point?

**Comment by gregg-miskelly** [comment]
@chuckries yes, when there is a breaking change

**Comment by gregg-miskelly** [comment]
@rajkumar42 Are you also going to update the script that we download in the SSH attach to process?

**Comment by rajkumar42** [comment]
@gregg-miskelly Yes I will update the script which is used in the SSH scenario when the clrdbg zips are available for all the distros.

**Pull request merged**
