### PR TITLE
Merge master into preview

### PR DESCRIPTION
**Pull request by chuckries**
For RC2 Release.

### CODE REVIEW

**Comment by chuckries** [comment]
@gregg-miskelly @caslan @wesrupert 

Not sure what the review protocol is for integrations. Please take a cursory look and make sure things look sane.

**Comment by gregg-miskelly** [comment]
No need to review. Just merge.

**Comment by chuckries** [comment]
@dotnet-bot build please

**Comment by chuckries** [comment]
@dotnet-bot build please

**Pull request merged**
