### PR TITLE
update clrdbg versions in GetClrDbg scripts

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
Tested the powershell script on windows and the shell script on ubuntu 14.04

**Comment by chuckries** [comment]
@gregg-miskelly

**Comment by gregg-miskelly** [comment]
You might want to double check with the version of MIEngine that we shipped in Update3 before you push this. Otherwise LGTM.

**Comment by rajkumar42** [comment]
:+1:

**Comment by chuckries** [comment]
I was able to verify that VS 2015 Update 3 along with the latest public docker tools for visual studio works with this change.

**Pull request merged**
