### PR TITLE
Allow lldb debugging on WSL attach

### PR DESCRIPTION
**Pull request by paulmaybee**

### CODE REVIEW

**Comment by WardenGnaw** [comment]
Do/Will we have docs or guide on how to use LLDB with WSL Attach? 

WSL will mostly (only?) be Unix and the issue is going to be a bunch of users will not have `lldb-mi` and we only have a version for macOS-x64.

**Comment by gregg-miskelly** [comment]
To be clear: WSL is only Linux

**Comment by paulmaybee** [comment]
@Erika ***@***.***> This comment is on the PR to add lldb support for WSL - in regards to this bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1407576/.

**Comment by paulmaybee** [comment]
Blog post for lldb is [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevblogs.microsoft.com%2Fcppblog%2Fattach-to-a-remote-process-with-lldb-in-visual-studio-2022-preview-3%2F&data=04%7C01%7Cpaulmay%40microsoft.com%7C81b02c9c94b942770a0d08d984610fbe%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637686374677131793%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HIh8LHdl8Hod8GzDYdzvYz1HAOqCydsxxc04gHZqoqU%3D&reserved=0). It includes a link to setting up lldb-mi on linux systems.

**Review by WardenGnaw — APPROVED** [review]
There can be an improvement on the error message to tell customers how to install `lldb-mi`.

This is the current error if you try to attach with lldb without `lldb-mi`.

image

**Output Window:**
image

**Review by gregg-miskelly — APPROVED** [review]

**Pull request merged**
