### PR TITLE
Limit fetching children to prevent hang with uninitialized data struc…

### PR DESCRIPTION
**Pull request by richardstanton**
…tures

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
This is a reasonable fix for build, but we should have a bug tracking a better long term fix (ex: adding a 'more' element).

**Comment by gregg-miskelly** [comment]
I think I might also suggest adding an element to the end indicating that the limit is reached unless that is really tricky to do.

**Comment by jacdavis** [comment]
The limit in the vs debugger is 5000. What was the motivation behind using 1000 here? Was 5000 too big?
We had previously spoken with Eric about his experience with this same problem in the EE and he had also suggested we need an expandable more element. I'm not sure it fits for build though like Gregg says.

**Comment by jacdavis** [comment]
Other than that, LGTM

**Comment by richardstanton** [comment]
Gregg, I agree that we do need a more long term fix, I tried to add a "truncated" element to the end of the list and it was trickier than I thought. I will investigate a more long term solution. Jackson, I initially tried 5000 elements, but the timeout was too long so I reduced it to 1000. Even with 1000 it still takes about 7 seconds to expand.

**Comment by richardstanton** [comment]
I learned how to add people to the pull request. I know some of you have already commented on this, but just for formality:
@gregg-miskelly @jacdavis @chuckries @paulmaybee

**Comment by richardstanton** [comment]
@dotnet-bot build please

**Comment by jacdavis** [comment]
@dotnet-bot build please

**Comment by chuckries** [comment]
@dotnet-bot build please

**Comment by jacdavis** [comment]
@dotnet-bot build please

**Comment by chuckries** [comment]
build machine appears to be in a bad state. I'm investigating.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Pull request merged**
