### PR TITLE
Fix for Frame's level=-1

### PR DESCRIPTION
**Pull request by pieandcakes**
* When frame's level=-1, make it 0 since it is represented by uint
* Fix spelling error

Fix for #144 

@paulmaybee @gregg-miskelly

### CODE REVIEW

**Comment by gregg-miskelly** [comment]
This feels like the wrong fix to me -- we use the frame id to control what frame we use in subsequent evaluations. So if we handle it this way we will wind up switching back to the root frame and issuing evaluations there. Seems like we should instead change this to a 'uint?' and implicitly fail any call that requires frame affinity.

**Comment by paulmaybee** [comment]
Can you reproduce this bug?  I have only seen it occur when the architecture of gdb was not matched with the architecture of gdbserver (for example trying to use an x86 gdb to debug remotely to an arm device).

**Comment by pieandcakes** [comment]
@paulmaybee yes, that is the exact instance I kept running into it.

**Comment by paulmaybee** [comment]
Then this in not the right fix. The right fix is to use the arm gdb.

**Comment by paulmaybee** [comment]
And by that I mean one compiled for x86 but targeting arm.

**Comment by pieandcakes** [comment]
We should probably also behave better by looking at Gregg's suggestion about `uint?` as the option. I will abandon this for now and might take a look again when I have time.

**Pull request closed without merging**
