### PR TITLE
Update clrdbg version numbers to latest

### PR DESCRIPTION
**Pull request by chuckries**

### CODE REVIEW

**Comment by chuckries** [comment]
@gregg-miskelly @rajkumar42 @dbreshears @NCarlsonMSFT

**Comment by chuckries** [comment]
This updates clrdbg for the script to the current version used in the 1.3 C# extension. This will be the final version (barring unforeseen issues) that the moniker VS2015U2 will refer to. The next official version of clrdbg will be dev15 based.

**Comment by rajkumar42** [comment]
:+1:

**Comment by chuckries** [comment]
I just want to be clear that merging this will update the version that is referenced in the script that is live in docker VS scenarios and the new version will be pulled down immediately. @dbresears is there testing you would like to do?

**Comment by gregg-miskelly** [comment]
@chuckries you did a quick test of the Docker tools scenario already?

Note that even though the next version of clrdbg will be Dev15 based, we can still use in in 2015 *if* we want to.

**Comment by dbreshears** [comment]
@chuckries yes, I can help do some testing.  Assume the location is -> https://raw.githubusercontent.com/chuckries/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh

**Comment by chuckries** [comment]
@gregg-miskelly I am smoke testing now.
@dbreshears yes.

**Comment by dbreshears** [comment]
@chuckries Looks good,  tested in our VS extension and VScode (Windows)

**Comment by NCarlsonMSFT** [comment]
Are there concerns for how this would work on the Mac in VS Code? My new Mac is not set up but I can prioritize that if it is needed.

**Comment by chuckries** [comment]
@NCarlsonMSFT the only difference is that windows would use the powershell script and mac would use the shell script. We don't have any issues currently for clrdbg on mac versus windows. If you want to try it out I can wait to merge this.

**Comment by dbreshears** [comment]
@chuckries Is there a pointer to what has changed or was fixed in this version
@NCarlsonMSFT I can test on my MAC tomorrow as it is sitting in the office and I am not

**Comment by NCarlsonMSFT** [comment]
@dbreshears did you ever remove my account from your Mac? If not I should still be able to use it.

**Comment by dbreshears** [comment]
@NCarlsonMSFT - its gone. Use your own MAC :-)

**Comment by chuckries** [comment]
[This page](https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp) contains a what's new in version 1.3 section that should cover it. Note that not all items in that last are specifically about clrdbg.

**Comment by NCarlsonMSFT** [comment]
I got my Mac configured and basic scenarios are working with the new script :shipit:

**Comment by chuckries** [comment]
Thanks everyone!

**Pull request merged**
