### PR TITLE
Updating Microsoft.VisualStudio.Linux.ConnectionManager.Contracts and…

### PR DESCRIPTION
**Pull request by rajkumar42**
Updating Microsoft.VisualStudio.Linux.ConnectionManager.Contracts and liblinux IL.
Removing duplicate stdout.

### CODE REVIEW

**Comment by rajkumar42** [comment]
@gregg-miskelly @caslan @wesrupert

**Comment by rajkumar42** [comment]
@itodirel

**Comment by caslan** [comment]
LGTM

**Comment by gregg-miskelly** [comment]
>                     _debuggerLaunched = true;

Your change will make it so that we no longer send this first line to _callback.OnStdOutLine

---
Refers to: src/MICore/Transports/UnixShellPortTransport.cs:143 in 9a3775f. [](commit_id = 9a3775f81fe7cb2874dc7fd8f932a8fa7202a039, deletion_comment = False)

**Comment by gregg-miskelly** [comment]
>             }

Can we remove this now?

---
Refers to: src/SSHDebugPS/AD7UnixAsyncCommand.cs:126 in 9a3775f. [](commit_id = 9a3775f81fe7cb2874dc7fd8f932a8fa7202a039, deletion_comment = False)

**Comment by gregg-miskelly** [comment]
Otherwise looks good to me

**Comment by rajkumar42** [comment]
>                     _debuggerLaunched = true;

Yep realized that :) Fix in my next iteration.

---
In reply to: [247150654](https://github.com/Microsoft/MIEngine/pull/442#issuecomment-247150654) [](ancestors = 247150654)

---
Refers to: src/MICore/Transports/UnixShellPortTransport.cs:143 in 9a3775f. [](commit_id = 9a3775f81fe7cb2874dc7fd8f932a8fa7202a039, deletion_comment = False)

**Pull request merged**
